# 1. Crear una función llamada imprimir_hola_mundo que imprima por
# pantalla el mensaje: “Hola Mundo!”. Llamar a esta función desde el
# programa principal.
## def imprimir_hola_mundo():
##     print('hola mundo')
## imprimir_hola_mundo()


# 2. Crear una función llamada saludar_usuario(nombre) que reciba
# como parámetro un nombre y devuelva un saludo personalizado.
# Por ejemplo, si se llama con saludar_usuario("Marcos"), deberá devolver: “Hola Marcos!”. 
# Llamar a esta función desde el programa
# principal solicitando el nombre al usuario.
# # def saludar_usuario(nombre):
# #     print(f'¡hola {nombre} que tal!!')
# # nombre_usuario=input('ingresa tu nombre: ')
# # saludar_usuario(nombre_usuario)


# 3. Crear una función llamada informacion_personal(nombre, apellido,
# edad, residencia) que reciba cuatro parámetros e imprima: “Soy
# [nombre] [apellido], tengo [edad] años y vivo en [residencia]”. 
# Pedir los datos al usuario y llamar a esta función con los valores ingresados.
# # def informacion_personal(nombre, apellido, edad, residencia):
# #     print(f'Soy {nombre} {apellido} tengo {edad} años y vivo en {residencia}')

# # nombreUsuario =input('Ingresa tu nombre: ')
# # apellido_usuario=input('Ingresa tu apellido: ')
# # edad_usuario= int(input('Ingrese su edad: '))
# # residencia_usuario=input('Ingrese su lugsr de residencia: ')
# # informacion_personal(nombreUsuario, apellido_usuario, edad_usuario, residencia_usuario)


# 4. Crear dos funciones: calcular_area_circulo(radio) que reciba el radio como parámetro 
# y devuelva el área del círculo. calcular_perimetro_circulo(radio) 
# que reciba el radio como parámetro y devuelva el perímetro del círculo. 
# Solicitar el radio al usuario y llamar ambas funciones para mostrar los resultados.
# # def calcular_area_circulo(radio):
# #     print(f'El área del círculo es: {3.1416 * (radio ** 2)}')

# # def calcular_perimetro_circulo(radio):
# #      print(f'El perimetro del círculo es: {2* 3.1416 * radio}')

# # calcular_radio= float(input('ingresa el raadio: '))
# # calcular_area_circulo(calcular_radio)
# # calcular_perimetro_circulo(calcular_radio)











